name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/NetuserPRO/android_kernel_xiaomi_mt6877
          depth: 1
          kernel-branch: workflow/lineage-21
          config: ruby_defconfig
          arch: arm64
          kvm: true
          aosp-clang: true
          android-version: 14
          aosp-clang-version: r487747c
